language: node_js
node_js: 10.15.0
cache: npm
script:
  - npm run linter;
  - npm run jest;
  - npm run coveralls;
  - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master